name: Build
on: [push, pull_request]

jobs:
  # Build lk2nd-msm8916 separately first to avoid booting lots of runners
  # for obvious build errors that affect all platforms
  lk2nd-msm8916:
    name: lk2nd
    uses: ./.github/workflows/lk2nd.yml
    with:
      project: lk2nd
      platform: msm8916
      artifacts: |
        build-*/lk.bin
        build-*/lk2nd.img
  lk2nd-sony:
    needs: lk2nd-msm8916
    uses: ./.github/workflows/lk2nd-matrix.yml
    with:
      project: lk2nd
      exclude: msm8916  
      artifacts: |
        build-*/lk.bin
        build-*/lk2nd.img
