name: Build lk2nd matrix
on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
      artifacts:
        type: string
        required: true
      exclude:
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - msm8974-aries
          - msm8974-leo
        exclude:
          - platform: ${{ inputs.exclude }}

    uses: ./.github/workflows/lk2nd.yml
    with:
      project: ${{ inputs.project }}
      platform: ${{ matrix.platform }}
      artifacts: ${{ inputs.artifacts }}
